### ISSUE TITLE
Connection status PLC

### ISSUE THREAD

**Issue by CommissarClippy** [mycroes/Sally7#37]
The PLC.TcpClient.Connected does not return a valid value for whether the PLC is currently connected. The value returns true before data could be actually read. Is there a way to actually check the connection status that the PLC is ready for communication? Currently I am simply repeating the read until I do not receive an exception.

**Comment by mycroes** [comment]
In addition to the comment from @gfoidl, if you perform an `Open()` (and it doesn't throw) and then check the `Connected` prop it should be `true`. At that point you actually are connected, I'm not sure if there's any way to check if the PLC is ready for communication.

In our applications we have a check whether exceptions are transient, but once I have successfully read a variable without any exception (retrying on transient exceptions only before that) I store that known-good state along the variable. If a PLC update is performed and there are intermittent address out of range exceptions I just ignore those and assume it'll all be good again at some point.

I'm closing this issue because I think it's all working as expected, but feel free to reopen with some more detail if you need further assistance.
