### ISSUE TITLE
Q: Comparsion to S7netPlus

### ISSUE THREAD

**Issue by MiroslavMikus** [mycroes/Sally7#7]
Hey,

we are using the [S7NetPlus](https://github.com/S7NetPlus/s7netplus) library in our project. Since you are one of the contributors to the S7NetPlus library and owner of Sally, there is no better person to ask.

- How do these two libraries compare to each other
- In which scenarios should I decide to use one over another

Thanks in advice
Best regards Miro

**Comment by mycroes** [comment]
Hi @MiroslavMikus,

Sorry for my incredibly late response. I have seen your message when you asked your question, but have forgotten to respond. In short, Sally7 has a very confined interface and currently (out of the box) only supports reading and writing of DataItems. However, Sally7 is very fast with reading and writing and offers strongly typed results. Also, Sally7 only offers async methods for reading and writing (because network communication is async).

S7NetPlus on the other hand has a convoluted API and tries to support many features, which in result means there's more code to maintain and it hasn't been properly maintained.

Both libraries work well. If Sally7 covers what you need I highly recommend Sally7. We're using it in production for a multitude of customers where performance matters. Sally7 is easy to consume (because the public API is small). Sally7 will permit you to have read/write cycles within 10ms, perhaps even less.

Let me know if you want more info.
